### ISSUE TITLE
G0blin not working after reboot.

### ISSUE THREAD

**Issue by soulspartan992** [Sticktron/g0blin#111]
Yesterday my 6s randomly rebooted, since then i haven't been successful with running g0blin again.

**Comment by peco77** [comment]
Reboots can happen since this jailbreak isn't fully stable yet. Last time it took me 45 minutes to rejailbreak after accidentally pressing reboot in cydia. So try to rejailbreak multiple times.

**Comment by jlbrkntr** [comment]
It can take quite a few tries to get it working and since it often crashes and reboots the device it can
take some time but it should work eventually, at least in my experience. Also, if the jailbreak app has
been on your device for a week or more then you need to install it once again using cydia impactor.

**Comment by Sticktron** [comment]
#15
