### ISSUE TITLE
G0blin needs re-sideloaded and trusted after each reboot

### ISSUE THREAD

**Issue by githubos1** [Sticktron/g0blin#255]
Hi,
iPhone 6, iOS 10.3.1, g0blin RC2

Every time I reboot my phone,  g0blin can not be opened anymore (closes right away). I need to re-sideload and re-trust my own AppleID certificate in order to run g0blin and re-jailbreak.
After successfull re-jailbreak (which btw always works instananeously) the certificate completely dispears in SETTINGS>General>Profile&Devices ... is that expected and normal behaviour ??

Thank's for some hints

**Comment by slenderhog** [comment]
Hey there,
iPhone 6S+, iOS 10.3.3, g0blin RC2

I had a similar issue on g0blin RC1 which resolved when I went up to RC2. In RC1 if you reboot your phone, the g0blin and Cydia (both app and all tweaks) remain on the phone, but the certificate is deleted. The same bug exists in RC2, though the certificate is still signed, g0blin will not be verified. Verifying it again works to open g0blin but not Cydia and g0blin would not re-jailbreak without an error almost immediately.

Ran into the same issue after a reboot a few days ago and just discovered this fix:
  [Your phone rebooted or ran out of power: don't fret, Cydia and all your tweaks are still installed, though Cydia cannot be opened. g0blin should open, though tapping "jailbreak" will fail immediately (on 10.3.3 at least).]
  1. Navigate to Settings > General > Device Management (Profile & Devices on lower iOS than 10.3.3) > "email when installed via Cydia Impactor".
  2. Click "Delete App" which will erase g0blin and the developer certificate from your phone. (Again, don't fret, CYDIA AND TWEAKS ARE STILL INSTALLED!) g0blin should no longer have an icon on the home screen.
  3. Jailbreak again via Cydia Impactor using the official g0blin_rc2.ipa.
  4. Re-trust your developer account (does not have to be the same account as before) and make sure g0blin says "Verified" next to it.
  5. Re-jailbreak through g0blin. It will auto-reboot if the jailbreak fails after 2 tries, but keep trying and you'll know you're jailbroken when the button is greyed out in the g0blin app. Sidenote: I read that hitting "jailbreak" when the CPU (far left) is 5% or below. To be safe, I hit the button at that time, the device rebooted and Cydia opened once again.
  6. Respring and your tweaks will all be back.

After a re-jailbreak, it's a useful moment to delete any tweaks causing complications on your phone before the respring, since you're essentially in safe mode. g0blin is still only a semi-jailbreak, but RC3 should resolve issues like this in the future.

Hope this is helpful!

**Comment by githubos1** [comment]
not really the same (as your "solution")
My tweeks and Cyda are all still on the phone,just the Certificate is gone and can not be re-trusted without sideloading it again :-((  once done and jailbroken again through g0blin, all is fine and Cydia and tweeks work just fine...
I mainly wonder if the dissapearance of the trusted certificate is normal behaviour ... or if there are tricks to prevent this from happening.

Except for gps issues the JB runs really stable...   see issue #114 and my issue there

**Comment by GeekBreak** [comment]
Do you have Immortal installed?

**Comment by slenderhog** [comment]
Well then I suppose the answer is "yes, this is normal behavior," as it did to me on RC1. Seems resolved in RC2, but you're running a different iOS, so I can't speak to that.

**Comment by githubos1** [comment]
YES I have immortal installed !!

btw, I'm not sure at all whether IMMORTAL will also work on the jailbreak itself ... should it ?? Does anyone know for sure ??  As I had to reboot and re-sideload and re-jailbreak again yesterday I will not know before next Friday (1 week from trusting my own certificate) if it will work ;-P
- provided no more reboots until then

**Comment by GeekBreak** [comment]
Immortal is the problem, it deletes the certificate embedded with the sideloaded app, uninstall it and you'll be fine

**Comment by githubos1** [comment]
will check over weekend and report :-)  Thank's
Only question remains...  would immortal prevent g0blin (and my own regular user AppleID certificate) from expiring after 1 week ??  in that case I would probably rather stick with it ... as I see further on less trouble with reboots and crashes..

**Comment by thekio1984** [comment]
i have a feeling you may have installed it while jailbroken..thats probably your issue...the certs injected with impactor, wont show if already in jb state..reboot to stock, then redo it, do NOT install anything via impactor when jailbroke, unless you have appsync installed & even then youll see no certs after ipa install.. afaik immortal will not stop the cert expiration, i believe it either autoresign or blocks the revoking process,either way the cert expires, but tbh any tweak like that is guna cause even more battery drain

**Comment by githubos1** [comment]
Ok... solved..  deleted IMMORTAL cydia app  and certificate now shows also after jailbreak !!

Thank you guys !!
