### ISSUE TITLE
10 versions of offsets for the iPhone 6s 10.3.3

### ISSUE THREAD

**Issue by JohnnyZer0** [Sticktron/g0blin#44]
Please, can someone give me the right offsets, because I found like 10 versions of offsets for my phone. Thanks. I managed to jailbroke once and then I installed winter board and I pressed reboot device (I am an idiot). And then I changed the offsets by mistake and yeah, long story short: offsets for iPhone 6s 10.3.3 N71mAP?

**Comment by robonxt** [comment]
Try using @xPreeks 's fork, he has offsets for some devices.

**Comment by JohnnyZer0** [comment]
I looked there, but he is missing some of the important ones; something like the last 3-4

**Comment by robonxt** [comment]
@JohnnyZer0 Sorry, then I'm not sure how to get them. I'm just a newbie here trying to help.
Also, what do you mean by "changed the offsets by mistakes"? Did you edit something to make your phone think it's a another model?

**Comment by zawata** [comment]
I used the offsets from the v0rtex-Nonce project: https://github.com/arx8x/v0rtexNonce/blob/master/v0rtexNonce/offsets.m

I'm on 6s 10.3.3.

**Comment by JohnnyZer0** [comment]
@robonxt no, I jailbreaked, and I thought it didn't work so I changed the offsets in the xcodeproject, but then the jailbreak worked and I forgot which offsets I used.
@zawata  ok, I'll try them

**Comment by pridhvi10** [comment]
I jailbroke successfully on the first try. installed a tweak and after installation it asked for 'reboot' instead of respring. I went ahead and rebooted the device. Now the G0blin app wont jailbreak. Either it restarts or says failed, try again. Please help!

I think my issue is the same as @JohnnyZer0  I'm a newbie. Someone please help me get the right offsets for my device iPhone 6s+ on iOS 10.3.3
